spring:

  datasource:

    username: root

    password: 157511442

    url: jdbc:mysql://localhost:3306/traceablity?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8

    driver-class-name: com.mysql.jdbc.Driver

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/templates/



